# Generated by Django 3.1.1 on 2020-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('DMgrade', models.CharField(default='NA', max_length=2)),
                ('DCgrade', models.CharField(default='NA', max_length=2)),
                ('COAgrade', models.CharField(default='NA', max_length=2)),
                ('SEgrade', models.CharField(default='NA', max_length=2)),
                ('PaSgrade', models.CharField(default='NA', max_length=2)),
                ('DSgrade', models.CharField(default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
