# Generated by Django 3.1 on 2020-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.EmailField(default='student@student.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rollNo',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(default=1947),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.EmailField(default='teacher@teacher.com', max_length=254, unique=True),
        ),
    ]
